### ISSUE TITLE
Extreme lag

### ISSUE THREAD

**Issue by VirxEC** [VirxEC/rl_ball_sym#1]
When calling `load_throwback_soccar()` and then generating ball prediction, generating each struct takes upwards of 70ms.

I've narrowed the issue down to the BvH, but I can't figure out what about either it or the primitives it contains is the issue.

**Comment by saintdev** [comment]
Here's a [flame graph](https://github.com/flamegraph-rs/flamegraph) of `load_throwback_soccar()` followed by calling `Ball::get_ball_prediction_struct_for_time()` 1000 times in a loop. Looks like about half the time is spent in `Bvh::intersect()` and half in `Tri::i...`. I'm unsure if it's `intersect_self()` or `intersect_sphere()`, as the name gets cut off.

Also, Throwback probably has the most geometry out of any of the maps, so it might just be that the BVH search just takes longer, because of the more complex geometry.

![flamegraph](https://user-images.githubusercontent.com/678111/143734432-77902790-d827-49c5-af13-a0dfd932c546.png)

**Comment by VirxEC** [comment]
It's `Tri::intersect_sphere()`. Tri has no `intersect_self`, only `Aabb` does.

**Comment by VirxEC** [comment]
Also, the hoops map has twice the number of triangles in it and generating the prediction on that is fine
